language: node_js
node_js: node

cache:
  directories:
    - .yarn/cache

install:
  - yarn

jobs:
  include:
    - name: "Test"
      before_script: yarn build
    - name: "Lint"
      script:
        - yarn lint
        - yarn flow
        - CHECK_COMPAT_DATA=1 yarn build-es-shims-data
